git:
  depth: 5
matrix:
  include:
    - language: node_js
      node_js:
        - '8'
        - '10'
      script:
        - yarn presubmit
      cache: yarn
      git:
        depth: 5

    - langauge: python
      python: 3.5
      script:
        - ./run_python_tests.sh
